spring:
  application:
    name: Projeto Final
  datasource:
    url: jdbc:h2:mem:projeto
    username: sa
    password: root
  jpa:
    hibernate:
      ddl-auto: update # Cria ou atualiza as tabelas automaticamente
    defer-datasource-initialization: true # Executa o data.sql após a criação das tabelas
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always # Garante que o data.sql seja executado